version: '3'

services:
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservice
    ports:
      - "8080:8080"
      - "9090:9090"

  wiremockserver:
    image: rodolpheche/wiremock
    volumes:
      - ./wiremock:/home/wiremock
    ports:
      - "8081:8080"

  masterlocust:
    build:
      context: ./locust
      dockerfile: Dockerfile.locust
    container_name: masterlocust
    environment:
      - "ATTACKED_HOST=http://microservice:8080"
      - "LOCUST_MODE=master"
    ports:
      - "8089:8089"
      - "5557:5557"
      - "5558:5558"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --name masterlocust --hostname masterlocust

  locustworker:
    build:
      context: ./locust
      dockerfile: Dockerfile.locust
    environment:
      - "ATTACKED_HOST=http://microservice:8080"
      - "NO_PROXY=masterlocust"
      - "LOCUST_MODE=slave"
      - "LOCUST_MASTER=masterlocust"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --name locustworker --link masterlocust