version: '3'

services:
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservice
    ports:
      - "8080:8080"
      - "9090:9090"

  wiremockserver:
    image: rodolpheche/wiremock
    volumes:
      - ./wiremock:/home/wiremock
    ports:
      - "8081:8080"

  locust:
    build:
      context: ./locust
      dockerfile: Dockerfile.locust
    container_name: locust
    environment:
      - "ATTACKED_HOST=http://microservice:8080"
    ports:
      - "8089:8089"

